In [1]:
import pandas as pd
import numpy as np
from itertools import combinations
from scipy import stats
from matplotlib import pyplot as plt
plt.style.use('seaborn-whitegrid')

## task 01

Объясняемая переменная y зависит от двух категориальных факторов A и B, причём фактор A имеет 3 уровня, а фактор B - 4 уровня. Результаты наблюдений приведены в таблице:

y = [[2.68, 3.29, 2.88, 4.45],
     [4.12, 4.96, 5.09, 5.22],
     [5.52, 4.50, 5.42, 5.29]]
С помощью двухфакторного дисперсионного анализа проверьте влияние каждого из факторов на переменную y.

In [2]:
y = np.array([[2.68, 3.29, 2.88, 4.45], [4.12, 4.96, 5.09, 5.22], [5.52, 4.50, 5.42, 5.29]])
y

array([[2.68, 3.29, 2.88, 4.45],
       [4.12, 4.96, 5.09, 5.22],
       [5.52, 4.5 , 5.42, 5.29]])

In [3]:
ya1 = y[0]
ya2 = y[1]
ya3 = y[2]

ya1, ya2, ya3

(array([2.68, 3.29, 2.88, 4.45]),
 array([4.12, 4.96, 5.09, 5.22]),
 array([5.52, 4.5 , 5.42, 5.29]))

In [4]:
yb1 = y.T[0]
yb2 = y.T[1]
yb3 = y.T[2]
yb4 = y.T[3]
yb1, yb2, yb3, yb4

(array([2.68, 4.12, 5.52]),
 array([3.29, 4.96, 4.5 ]),
 array([2.88, 5.09, 5.42]),
 array([4.45, 5.22, 5.29]))

In [5]:
ya1_mean = ya1.mean() # по строкам
ya2_mean = ya2.mean()
ya3_mean = ya3.mean()

ya1_mean, ya2_mean, ya3_mean

(3.325, 4.8475, 5.1825)

In [6]:
yb1_mean = yb1.mean() # по столбцам
yb2_mean = yb2.mean()
yb3_mean = yb3.mean()
yb4_mean = yb4.mean()

yb1_mean, yb2_mean, yb3_mean, yb4_mean

(4.1066666666666665, 4.25, 4.463333333333334, 4.986666666666667)

In [7]:
Y = np.concatenate([ya1, ya2, ya3, yb1, yb2, yb3, yb4])
Y

array([2.68, 3.29, 2.88, 4.45, 4.12, 4.96, 5.09, 5.22, 5.52, 4.5 , 5.42,
       5.29, 2.68, 4.12, 5.52, 3.29, 4.96, 4.5 , 2.88, 5.09, 5.42, 4.45,
       5.22, 5.29])

In [8]:
Y_mean = Y.mean()
Y_mean

4.451666666666666

In [9]:
k = 4
m = 3

In [10]:
SS_a = k * ((ya1_mean - Y_mean) ** 2 + (ya2_mean - Y_mean) ** 2 + (ya3_mean - Y_mean) ** 2)

SS_b = m * ((yb1_mean - Y_mean) ** 2 + (yb2_mean - Y_mean) ** 2 + (yb3_mean - Y_mean) ** 2 + (yb4_mean - Y_mean) ** 2)

SS_w = ((ya1 - ya1_mean - yb1_mean + Y_mean) ** 2).sum() + ((ya1 - ya1_mean - yb2_mean + Y_mean) ** 2).sum() + ((ya1 - ya1_mean - yb3_mean + Y_mean) ** 2).sum() + ((ya1 - ya1_mean - yb4_mean + Y_mean) ** 2).sum() + ((ya2 - ya2_mean - yb1_mean + Y_mean) ** 2).sum() + ((ya2 - ya2_mean - yb2_mean + Y_mean) ** 2).sum() + ((ya2 - ya2_mean - yb3_mean + Y_mean) ** 2).sum() + ((ya2 - ya2_mean - yb4_mean + Y_mean) ** 2).sum() + ((ya3 - ya3_mean - yb1_mean + Y_mean) ** 2).sum() + ((ya3 - ya3_mean - yb2_mean + Y_mean) ** 2).sum() + ((ya3 - ya3_mean - yb3_mean + Y_mean) ** 2).sum() + ((ya3 - ya3_mean - yb4_mean + Y_mean) ** 2).sum()

        
SS_a, SS_b, SS_w

(7.8407166666666654, 1.338166666666669, 18.424866666666674)

In [11]:
sigma2_a = SS_a / (m - 1)
sigma2_b = SS_b / (k - 1)
sigma2_w = SS_w / ((k - 1) * (m - 1))

sigma2_a, sigma2_b, sigma2_w

(3.9203583333333327, 0.4460555555555563, 3.0708111111111123)

In [12]:
F_a = sigma2_a / sigma2_w
F_b = sigma2_b / sigma2_w
F_a, F_b

(1.276652386448748, 0.1452565916352178)

In [13]:
k1a = m - 1
k2a = m * k - m
k1a, k2a

(2, 9)

In [14]:
k1b = k - 1
k2b = m * k - k
k1b, k2b

(3, 8)

In [15]:
alpha = 0.05

t_a = stats.f.ppf(1 - alpha, k1a, k2a)
t_b = stats.f.ppf(1 - alpha, k1b, k2b)
t_a, t_b

(4.25649472909375, 4.06618055135116)

Значения статистик не попадают в критические области, оба фактора не влияют на значение y